FROM php:5.6.36-apache-stretch

RUN apt-get update && apt-get install -y libpq-dev libfreetype6-dev libjpeg62-turbo-dev libmcrypt-dev libpng-dev libzip-dev \
	&& docker-php-ext-install pdo_mysql pdo_pgsql mbstring zip bcmath

RUN a2enmod rewrite && service apache2 restart

RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
 && php composer-setup.php --install-dir=/usr/bin --filename=composer \
 && php -r "unlink('composer-setup.php');" \
 && export PATH=$PATH:~/.composer/vendor/bin

ENV APACHE_DOCUMENT_ROOT /var/www/html/public

RUN sed -ri -e 's!/var/www/html!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/sites-available/*.conf \
    && sed -ri -e 's!/var/www/!${APACHE_DOCUMENT_ROOT}!g' /etc/apache2/apache2.conf /etc/apache2/conf-available/*.conf \
    && rm /var/log/apache2/access.log
